{
 "title": "Java EE Porcupine Bulkheads",
 "description": "Displays the instrumentation of Java EE Porcupine executor services.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipelines",
    "query": "metrics([^_]*porcupine_pipelines.*_core_pool_size)"
   }
  ]
 },
 "panels": [
  { "title": "Pipeline: $pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pipelines" },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vendor:porcupine_pipelines_${pipelines}_tasks_total[30s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(vendor:porcupine_pipelines_${pipelines}_tasks_rejected[30s]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:porcupine_pipelines_${pipelines}_current_thread_pool_size",
     "legendFormat": "Pool size"
    },
    {
     "expr": "vendor:porcupine_pipelines_${pipelines}_active_thread_count",
     "legendFormat": "Active threads"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:porcupine_pipelines_${pipelines}_remaining_queue_capacity",
     "legendFormat": "Remaining slots"
    }
   ]
  }
 ]
}